language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t shidlovsky/docker-test -f Dockerfile.dev .
scripts:
  - docker run -e CI=true shidlovsky/docker-test npm run test